### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by eezstreet** [midgen/GOAPer#3]
It would appear that there is a chunk of code causing a crash occasionally when opening a Controller or Action window.

Specifically, if [this](https://github.com/midgen/GOAPer/blob/master/Source/GOAPerEditor/Private/DetailCustomizations/GOAPStateCustomization.cpp#L51) chunk of code gets executed, then [this](https://github.com/midgen/GOAPer/blob/master/Source/GOAPerEditor/Private/DetailCustomizations/GOAPStateCustomization.cpp#L74) will cause an Array Out of Bounds exception.

I'm not too familiar with Slate programming, but commenting out the second line seemed to solve the crash for me.

**Comment by midgen** [comment]
c018111c1d1e481f6951ef9899ed485ca9d0f749

Added assert when no options are configured.
